import {
  Twitter,
  Instagram,
  Cookie as Google,
  Linkedin,
  Bot,
  MessageSquare,
  Users,
  TrendingUp,
  Settings,
  LogOut,
  Bell,
  Eye,
  ThumbsUp,
  Send,
  Clock,
  CheckCircle,
  XCircle,
} from "lucide-react"

export const Icons = {
  twitter: Twitter,
  instagram: Instagram,
  google: Google,
  linkedin: Linkedin,
  bot: Bot,
  message: MessageSquare,
  users: Users,
  trending: TrendingUp,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  eye: Eye,
  thumbsUp: ThumbsUp,
  send: Send,
  clock: Clock,
  checkCircle: CheckCircle,
  xCircle: XCircle,
}
